# based on
# https://blog.softwaremill.com/running-akka-cluster-on-kubernetes-e4cd2913e951
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka-simple-cluster
spec:
  replicas: 5
  selector:
    matchLabels:
      app: akka-simple-cluster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: akka-simple-cluster
    spec:
      containers:
      - image: davarski/akka-simple-cluster-k8s:0.2
        imagePullPolicy: IfNotPresent
        name: akka-simple-cluster
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        - name: remoting
          containerPort: 2551
        - name: api
          containerPort: 8080
        - name: management
          containerPort: 8558
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
