# based on
# https://blog.softwaremill.com/running-akka-cluster-on-kubernetes-e4cd2913e951
kind: Service
apiVersion: v1
metadata:
  name: akka-simple-cluster
spec:
  type: NodePort
  selector:
    app: akka-simple-cluster
  ports:
  - protocol: TCP
    name: management
    port: 8558
    targetPort: management
  - protocol: TCP
    name: api
    port: 8080
    targetPort: api
